substitutions: # per device-specific substitutions (copy this only to the esphome web ui)
  static_ip:                            # set to the target ip address of the device
  use_address: ${static_ip}             # set to the current ip address of the device for OTA flashing
  api_key:
  ota_password: !secret ota_password
  log_level: none
  web_server_ota: true                  # enable ota in the web server.
  esp_wifi_scan_internal: false         # set to false to show the full wifi scan results

  wifi_ssid_1:          !secret wifi_ssid
  wifi_ssid_1_password: !secret wifi_password
  wifi_ssid_2:          !secret uly_wifi_ssid
  wifi_ssid_2_password: !secret uly_wifi_password
  gateway:              !secret gateway           # Set this to the IP address of the router. Often ends with .1
  subnet:               !secret subnet            # The subnet of the network

  dns_domain: ".local"                            # Define the domain for this device. example: .local (device will appear as xxx-xxxxx.local in DNS/DHCP logs)
  wifi_fast_connect: "false"                      # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  ap_timeout: 1min
  power_save_mode: none
  reboot_timeout: 2min
  flash_write_interval: 10min

  timezone: ""                                    # Set timezone of the device. Can be entered in unix Country/Area format (i.e. "Australia/Sydney")
  esp_wifi_scan_internal: true                    # set to false to show the full wifi scan results

packages:
  device_base: github://Cahlil-Togonon/Smart-iLAB/***   # add the correct path to the yaml file.