substitutions: # per device-specific substitutions (copy this only to the esphome web ui)
  static_ip:                            # set to the target ip address of the device
  use_address: ${static_ip}             # set to the current ip address of the device for OTA flashing
  api_key:
  ota_password: !secret ota_password
  log_level: none
  web_server_ota: true                  # enable ota in the web server.
  esp_wifi_scan_internal: false         # set to false to show the full wifi scan results

packages:
  air_gradient:                                           # add meaningful package name
    url: https://github.com/Cahlil-Togonon/Smart-iLAB     # github repo
    ref: main                                             # branch name
    file: Air-Gradient/AG-one.yaml                        # file directory of device 
    refresh: 5min                                         # refresh frequency to check for device updates