substitutions: # per device-specific substitutions (copy this only to the esphome web ui)
  static_ip:                            # set to the target ip address of the device
  use_address:                          # set to the current ip address of the device for OTA flashing
  api_key:
  ota_password: !secret ota_password
  log_level: DEBUG
  web_server_ota: true                  # enable ota in the web server.
  esp_wifi_scan_internal: true          # set to false to show the full wifi scan results

packages:
  device_name:                                            # add meaningful package name
    url: https://github.com/Cahlil-Togonon/Smart-iLAB     # github repo
    ref: main                                             # branch name
    file:                                                 # file directory of device 
    refresh: 5min                                         # refresh frequency to check for device updates