substitutions: # per device-specific substitutions (copy this only to the esphome web ui)
  static_ip:                            # set to the target ip address of the device
  use_address: ${static_ip}             # set to the current ip address of the device for OTA flashing
  api_key:
  ota_password: !secret ota_password
  log_level: none
  web_server_ota: true                  # enable ota in the web server.
  esp_wifi_scan_internal: false         # set to false to show the full wifi scan results

packages:
  device_base: github://Cahlil-Togonon/Smart-iLAB/***   # add the correct path to the yaml file.