substitutions:
  name: athom-smart-plug-v2-9d3535
  friendly_name: Smart Plug V2 9d3535
packages:
  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: avf1lJOfgJULcrpDHltNyWk/4SVHY79LmyydFiOUQo0=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
