sensor:
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 30s
    entity_category: "diagnostic"

  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic

  # - platform: internal_temperature
  #   name: "ESP Temperature"
  #   id: sys_esp_temperature
  #   entity_category: "diagnostic"

  - platform: uptime
    name: Uptime
    id: uptime_sensor
    update_interval: 60s
    entity_category: "diagnostic"