# AirGradient ONE - Board v9
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: "ag-one"
  friendly_name: "AG One"
  config_version: 2.0.1

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${friendly_name}"
  name_add_mac_suffix: true             # recommended: use mac address as differentiator

# device base packages
packages:
  device_base:      github://Cahlil-Togonon/Smart-iLAB/packages/device_base.yaml@main
  wifi:             github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/wifi.yaml@main
  api:              github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/api.yaml@main
  ota:              github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/ota.yaml@main
  logger:           github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/logger.yaml@main
  # web_server:       github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/web_server.yaml@main
  binary_sensor:    github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/binary_sensor.yaml@main
  sensor:           github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/sensor.yaml@main
  button:           github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/button.yaml@main
  text_sensor:      github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/text_sensor.yaml@main
  time:             github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/time.yaml@main

  # Air Gradient packages from MallocArray
  board: github://MallocArray/airgradient_esphome/packages/airgradient_esp32-c3_board.yaml
  pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003.yaml
  co2: github://MallocArray/airgradient_esphome/packages/sensor_s8.yaml
  temp_humidity: github://MallocArray/airgradient_esphome/packages/sensor_sht40.yaml
  tvoc: github://MallocArray/airgradient_esphome/packages/sensor_sgp41.yaml
  display: github://MallocArray/airgradient_esphome/packages/display_sh1106_multi_page.yaml
  led: github://MallocArray/airgradient_esphome/packages/led.yaml
  led_co2: github://MallocArray/airgradient_esphome/packages/led_co2.yaml
  airgradient_api: github://MallocArray/airgradient_esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: github://MallocArray/airgradient_esphome/packages/watchdog.yaml
  config_button: github://MallocArray/airgradient_esphome/packages/config_button.yaml
  wifi_sensor: github://MallocArray/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://MallocArray/airgradient_esphome/packages/sensor_uptime.yaml
  safe_mode: github://MallocArray/airgradient_esphome/packages/switch_safe_mode.yaml

binary_sensor:
  - id: !extend config_button
    pin:
      ignore_strapping_warning: true  # Acknowledging that this is a strapping pin and should not have external pullup/down resistors  https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins