substitutions: # generic substitutions
  dns_domain: ".local"                            # Define the domain for this device. example: .local (device will appear as xxx-xxxxx.local in DNS/DHCP logs)
  wifi_fast_connect: "false"                      # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  wifi_ssid_1:          !secret wifi_ssid
  wifi_ssid_1_password: !secret wifi_password
  wifi_ssid_2:          !secret uly_wifi_ssid
  wifi_ssid_2_password: !secret uly_wifi_password
  gateway:              !secret gateway           # Set this to the IP address of the router. Often ends with .1
  subnet:               !secret subnet            # The subnet of the network
  ap_timeout: 1min
  power_save_mode: none
  reboot_timeout: 2min
  flash_write_interval: 10min

  timezone: ""                                    # Set timezone of the device. Can be entered in unix Country/Area format (i.e. "Australia/Sydney")
  esp_wifi_scan_internal: true                    # set to false to show the full wifi scan results

# esphome:
#   name: ${device_id}
#   build_path: ./build/${device_id}

# ${platform}:
#   board: ${board}

# preferences:
#   flash_write_interval: ${flash_write_interval}

packages:
  wifi:             github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/wifi.yaml
  api:              github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/api.yaml
  ota:              github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/ota.yaml
  logger:           github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/logger.yaml
  web_server:       github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/web_server.yaml
  binary_sensor:    github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/binary_sensor.yaml
  sensor:           github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/sensor.yaml
  button:           github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/button.yaml
  text_sensor:      github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/text_sensor.yaml
  time:             github://Cahlil-Togonon/Smart-iLAB/packages/base_packages/time.yaml